apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-ds
  labels:
    app: test-ds
spec:
  selector:
    matchLabels:
      app: test-ds
  template:
    metadata:
      labels:
        app: test-ds
    spec:
      containers:
        - name: test-ds
          image: traefik:2.3
          imagePullPolicy: Never
          args:
            - --configfile=/config/test-ds.toml
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /ping
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /config
              name: config
      terminationGracePeriodSeconds: 60
      serviceAccount: test-ds
      volumes:
        - configMap:
            defaultMode: 420
            name: test-ds
          name: config
---
