name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Checkout Code
        uses: actions/checkout@v2

      - run: du -d 4

      - name: Build
        run: BUILD.sh

      - uses: actions/upload-artifact@v2
        with:
          name: ruckstack-builders
          path: |
            ~/work/ruckstack/ruckstack/out/artifacts
