name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: bash BUILD.sh compile

      - name: Test
        run: bash BUILD.sh test

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ruckstack-${{ format(github.head_ref, 'refs/heads/', '') }}.zip
          path: |
            ~/work/ruckstack/ruckstack/out/artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          file: out/image/Dockerfile
          context: out/builder_image
          push: true
          tags: ghcr.io/ruckstack/ruckstack:${{ format(github.head_ref, 'refs/heads/', '') }}